### ISSUE TITLE
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long

### ISSUE THREAD

**Issue by Sfeeen** [rushiiMachine/XSpoofSignatures#1]
I installed LSposed and XspoofSignatures (only module installed).
I resigned an app and added the original signature in the meta values. The signature doesn't seem to be changed (I check it using Frida).
When I look at the Xposed logs I find:

`
12-24 23:54:01.687  1012  2506 E LSPosed-Bridge: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
12-24 23:54:01.687  1012  2506 E LSPosed-Bridge: 	at dev.materii.rushii.xspoofsignatures.Main$1.afterHookedMethod(Unknown Source:14)
12-24 23:54:01.687  1012  2506 E LSPosed-Bridge: 	at axc.MY.lKv.RlpHxNAZybt.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
12-24 23:54:01.687  1012  2506 E LSPosed-Bridge: 	at J.callback(Unknown Source:292)
12-24 23:54:01.687  1012  2506 E LSPosed-Bridge: 	at LSPHooker_.generatePackageInfo(Unknown Source:25)
12-24 23:54:01.687  1012  2506 E LSPosed-Bridge: 	at com.android.server.pm.PackageManagerService$ComputerEngine.getPackageInfoInternalBody(PackageManagerService.java:4002)
12-24 23:54:01.687  1012  2506 E LSPosed-Bridge: 	at com.android.server.pm.PackageManagerService$ComputerEngine.getPackageInfoInternal(PackageManagerService.java:3951)
12-24 23:54:01.687  1012  2506 E LSPosed-Bridge: 	at com.android.server.pm.PackageManagerService$ComputerEngine.getPackageInfo(PackageManagerService.java:3934)
12-24 23:54:01.687  1012  2506 E LSPosed-Bridge: 	at com.android.server.pm.PackageManagerService$ComputerTracker.getPackageInfo(PackageManagerService.java:5964)
12-24 23:54:01.687  1012  2506 E LSPosed-Bridge: 	at com.android.server.pm.PackageManagerService.getPackageInfo(PackageManagerService.java:10050)
12-24 23:54:01.687  1012  2506 E LSPosed-Bridge: 	at android.content.pm.PackageManager.getPackageInfoAsUserUncached(PackageManager.java:9699)
12-24 23:54:01.687  1012  2506 E LSPosed-Bridge: 	at android.content.pm.PackageManager.access$100(PackageManager.java:117)
12-24 23:54:01.687  1012  2506 E LSPosed-Bridge: 	at android.content.pm.PackageManager$2.recompute(PackageManager.java:9712)
12-24 23:54:01.687  1012  2506 E LSPosed-Bridge: 	at android.content.pm.PackageManager$2.recompute(PackageManager.java:9709)
12-24 23:54:01.687  1012  2506 E LSPosed-Bridge: 	at android.app.PropertyInvalidatedCache.query(PropertyInvalidatedCache.java:498)
12-24 23:54:01.687  1012  2506 E LSPosed-Bridge: 	at android.content.pm.PackageManager.getPackageInfoAsUserCached(PackageManager.java:9727)
12-24 23:54:01.687  1012  2506 E LSPosed-Bridge: 	at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:288)
12-24 23:54:01.687  1012  2506 E LSPosed-Bridge: 	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:265)
12-24 23:54:01.687  1012  2506 E LSPosed-Bridge: 	at com.samsung.android.server.wifi.softap.smarttethering.SemWifiApSmartUtil.isPackageExists(SemWifiApSmartUtil.java:552)
12-24 23:54:01.687  1012  2506 E LSPosed-Bridge: 	at com.samsung.android.server.wifi.softap.smarttethering.SemWifiApSmartBleScanner.checkPreConditions(SemWifiApSmartBleScanner.java:1318)
12-24 23:54:01.687  1012  2506 E LSPosed-Bridge: 	at com.samsung.android.server.wifi.softap.smarttethering.SemWifiApSmartBleScanner.startBleScanning(SemWifiApSmartBleScanner.java:909)
12-24 23:54:01.687  1012  2506 E LSPosed-Bridge: 	at com.samsung.android.server.wifi.softap.smarttethering.SemWifiApSmartBleScanner$BleWorkHandler.handleMessage(SemWifiApSmartBleScanner.java:1110)
12-24 23:54:01.687  1012  2506 E LSPosed-Bridge: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-24 23:54:01.687  1012  2506 E LSPosed-Bridge: 	at android.os.Looper.loopOnce(Looper.java:226)
12-24 23:54:01.687  1012  2506 E LSPosed-Bridge: 	at android.os.Looper.loop(Looper.java:313)
12-24 23:54:01.687  1012  2506 E LSPosed-Bridge: 	at android.os.HandlerThread.run(HandlerThread.java:67)

`

**Comment by rushiiMachine** [comment]
1. what android version
2. what rom

**Comment by Sfeeen** [comment]
1. Android version 12
2. samsung galaxy A12 SM-a127/DSN (Stock ROM)

I must say, I am not sure if there's a bug in this module or if I messed up in my setup. I do not understand the log stacktrace but since the second line says something about the  dev.materii.rushii.xspoofsignatures.Main$1.afterHookedMethod method of your module I made this issue

**Comment by IGProd** [comment]
can you please support android 14 or change sdk because i can not longer installed on coloros android 14 because of signature 
1. Android 14 Coloros 
2. Oneplus 9 pro
